version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    #ports:
    #  - 27017:27017
    volumes:
      - ./mongo-volume:/data/db


#volumes:
#  mongodb_data_container:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app

    depends_on:
      - mongo


